//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaifPortFoliio.Admin
{
    public partial class Role
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label formTitle;

        protected global::System.Web.UI.WebControls.HiddenField hfRoleId;

        protected global::System.Web.UI.WebControls.TextBox txtRoleText;

        protected global::System.Web.UI.WebControls.Button btnSave;

        protected global::System.Web.UI.WebControls.Button btnCancel;

        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMessage;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.GridView gvRoles;
    }
}
